
export const offersColumns = [
  { headerName: 'ID пропозиції', field: 'offerId' },
  { headerName: 'КП внесено', field: 'isImported' },
  { headerName: 'ПДЗ', field: 'pdz' },
  { headerName: 'Вид пропозиції', field: 'type' },
  { headerName: 'Іноземці', field: 'isForeigners' },
  { headerName: 'Особливий вступ', field: 'isSpecialIntroduction' },
  { headerName: 'Назва пропозиції', field: 'name' },
  { headerName: 'Освітній ступінь', field: 'educationalDegree' },
  { headerName: 'Вступ на основі', field: 'admissionBased' },
  { headerName: 'Форма навчання', field: 'studyForm' },
  { headerName: 'Курс', field: 'course' },
  { headerName: 'Код спеціальності', field: 'specialtyCode' },
  { headerName: 'Спеціальність', field: 'specialty' },
  { headerName: 'Спеціалізація', field: 'specialization' },
  { headerName: 'Тип програми магістра', field: 'masterType' },
  { headerName: 'Освітні програми', field: 'educationalPrograms' },
  { headerName: 'Структурний підрозділ', field: 'structuralUnit' },
  { headerName: 'Скорочений термін', field: 'isShortenedTerm' },
  { headerName: 'Термін навчання', field: 'studyPeriod' },
  { headerName: 'Початок навчання', field: 'studyStart', },
  { headerName: 'Закінчення навчання', field: 'studyEnd', },
  { headerName: 'Дата застосування пропозиції', field: 'dateApplication', },
  { headerName: 'Дата останньої зміни', field: 'lastChange', },
  { headerName: 'Дата завантаження ліцензії', field: 'licenseDownload', },
  { headerName: 'Підстава ліцензії', field: 'licenseBasis' },
  { headerName: 'МінКБР', field: 'minKBR' },
  { headerName: 'Регіональне замовлення від', field: 'regionalOrder' },
];

export const statementsColumns = [
  { headerName: 'Ід заявки', field: 'statementId' },
  { headerName: 'Ід персони', field: 'personaId' },
  { headerName: 'Тип пропозиції', field: 'proposeType' },
  { headerName: 'Чи іноземець', field: 'isForeigner' },
  { headerName: 'Назва КП', field: 'offerName' },
  { headerName: 'ОКР', field: 'okr' },
  { headerName: 'Вступ на основі', field: 'admissionBased' },
  { headerName: 'Спеціальність', field: 'specialty' },
  { headerName: 'Спеціалізація', field: 'specialization' },
  { headerName: 'Форма навчання', field: 'studyForm' },
  { headerName: 'Курс', field: 'course' },
  { headerName: 'Структурний підрозділ', field: 'structuralUnit' },
  { headerName: 'Чи скорочений термін навчання', field: 'isTrainingPeriodReduced' },
  { headerName: 'Чи електронна заява', field: 'isElectronicApplication' },
  { headerName: 'Вступник', field: 'statement' },
  { headerName: 'Контактний номер', field: 'contactNumber' },
  { headerName: 'Електронна адреса', field: 'electronicAddress' },
  { headerName: 'Стать', field: 'sex' },
  { headerName: 'Чи громадянин України', field: 'isCitizenOfUkraine' },
  { headerName: 'Статус заявки', field: 'statementStatus' },
  { headerName: 'Номер (шифр) особової справи', field: 'personalFileCode' },
  { headerName: 'Конкурсний бал', field: 'competitiveScore' },
  { headerName: 'Пріоритет', field: 'priority' },
  { headerName: 'Черговість в рейтингу з однаковою кількістю балів', field: 'sequenceRankingSameNumberOfPoints' },
  { headerName: 'Бере участь в конкурсі на місця державного та регіонального замовлення', field: 'isParticipatesCompetitionStateOrRegional' },
  { headerName: 'Бере участь в конкурсі на місця за кошти фізичних та юридичних осіб', field: 'isParticipatesCompetitionIndividualsOrLegal' },
  { headerName: 'Тип конкурсу, за яким отримано рекомендацію', field: 'typeCompetitionRecomendation' },
  { headerName: 'Чи рекомендовано за співбесідою', field: 'isRecommendedByInterview' },
  { headerName: 'Чи подано оригінал', field: 'isOriginalSubmitted' },
  { headerName: 'Чи подано довідку про місцезнаходження оригіналів', field: 'isLocationOriginalsProvided' },
  { headerName: 'Категорія заяви іноземця', field: 'categoryForeigner' },
  { headerName: 'Пільгові категорії', field: 'preferentialCategories' },
  { headerName: 'Номер акту', field: 'actNumber' },
  { headerName: 'Причини скасування', field: 'cancelReason' },
  { headerName: 'Особа претендує на зарахування 200 балів', field: 'isPersonClaims200' },
  { headerName: 'Особа претендує на застосування сільського коефіцієнту', field: 'isPersonVillageСoef' },
  { headerName: 'Претендує на квоту 3', field: 'isPretendQuota3' },
  { headerName: 'Наказ про зарахування', field: 'enrollmentOrder' },
  { headerName: 'Причини відрахування', field: 'deductionReasons' },
  { headerName: 'Претендує на контракт', field: 'isPretendContract' },
  { headerName: 'Претендує на бюджет', field: 'isPretendBudget' },
  { headerName: 'Причина допуску лише на контракт', field: 'reasonForContractOnly' },
  { headerName: "Опис причини допуску лише на контракт для причини 'Інша'", field: 'reasonForContractOnlyOther' },
  { headerName: 'Чи здобувався ОКР уже за бюджет', field: 'isObtainedForBudget' },
  { headerName: 'Право здобувати іншу освіту за бюджет', field: 'receiveOtherEducationForBudget' },
  { headerName: 'Чи вступ на ту саму або споріднену галузь', field: 'isIntroductionToTheSame' },
  { headerName: 'Чи здобуває ступінь(рівень) або вищий', field: 'isGetDegree' },
  { headerName: 'Чи потрібно пройти додаткові вступні випробування', field: 'isNeedToPassAdditionalExams' },
  { headerName: 'Тип документа', field: 'documentType' },
  { headerName: 'Серія документа', field: 'documentSeries' },
  { headerName: 'Номер документа', field: 'documentNumber' },
  { headerName: 'Дата видачі документа', field: 'documentIssuanceDate' },
  { headerName: 'Ким видано', field: 'documentIssuedBy' },
  { headerName: 'Відзнака', field: 'honor' },
  { headerName: 'Сканкопія додана', field: 'isScanningAdded' },
  { headerName: 'Час додання заяви до ЄДЕБО', field: 'addedTimeInEDEBO' },
  { headerName: 'Потрібно внести зміни в ЗНО', field: 'isNeedChangeZNO' },
  { headerName: 'Чи рекомендовано за результатом адресного розміщення державного замовлення', field: 'isRecommendedByResultOfAddressBudgetOrder' },
  { headerName: 'Тип конкурсу, за яким одержано рекомендацію за результатом адресного розміщення ДЗ', field: 'typeCompetitionRecomendationOfAddress' },
  { headerName: 'Пріоритет заяви, яка отримала рекомендацію за результатом адресного розміщення ДЗ', field: 'priorityStatement' },
  { headerName: 'Чи отримав рекомендацію на анульовану конкурсну пропозицію, за результатом адресного розміщення державного замовлення', field: 'isRecommendedOnCanceled' },
  { headerName: 'Час останньої зміни', field: 'lastTimeChange' },
  { headerName: 'Додав заяву', field: 'addedStatement' },
  { headerName: 'Середній бал документа про освіту', field: 'averageEducationDocumentScore' },
  { headerName: 'ЗНО.Українська мова', field: 'znoUkrainian' },
  { headerName: 'ЗНО.Українська мова та література', field: 'znoUkrainianLiterature' },
  { headerName: 'ЗНО.Історія України', field: 'znoUkrainianHistory' },
  { headerName: 'ЗНО.Математика', field: 'znoMathematics' },
  { headerName: 'ЗНО.Біологія', field: 'znoBiology' },
  { headerName: 'ЗНО.Географія', field: 'znoGeography' },
  { headerName: 'ЗНО.Фізика', field: 'znoPhysics' },
  { headerName: 'ЗНО.Хімія', field: 'znoChemistry' },
  { headerName: 'ЗНО.Англійська мова', field: 'znoEnglish' },
  { headerName: 'ЗНО.Французька мова', field: 'znoFrench' },
  { headerName: 'ЗНО.Німецька мова', field: 'znoGerman' },
  { headerName: 'ЗНО.Іспанська мова', field: 'znoSpanish' },
  { headerName: 'ДПО', field: 'dpo' },
  { headerName: 'ДПО.Серія', field: 'dpoSeries' },
  { headerName: 'ДПО.Номер', field: 'dpoNumber' },
  { headerName: 'ДПО.Дата видачі', field: 'dpoIssueDate' },
  { headerName: 'ДПО.Дійсний до', field: 'dpoValidUntil' },
  { headerName: 'РНОКПП', field: 'rnokpp' },
];
