
export const offersColumns = [
  { headerName: 'ID пропозиції', field: 'offerId' },
  { headerName: 'КП внесено', field: 'isImported', selected: ['так', 'ні'] },
  { headerName: 'ПДЗ', field: 'pdz' },
  { headerName: 'Вид пропозиції', field: 'type', selected: ['Фіксована', 'Небюджетна', 'Відкрита'] },
  { headerName: 'Іноземці', field: 'isForeigners', selected: ['так', 'ні'] },
  { headerName: 'Особливий вступ', field: 'isSpecialIntroduction' },
  { headerName: 'Назва пропозиції', field: 'name' },
  { headerName: 'Освітній ступінь', field: 'educationalDegree' },
  { headerName: 'Вступ на основі', field: 'admissionBased' },
  { headerName: 'Форма навчання', field: 'studyForm', selected: ['Денна', 'Заочна'] },
  { headerName: 'Курс', field: 'course' },
  { headerName: 'Код спеціальності', field: 'specialtyCode' },
  { headerName: 'Спеціальність', field: 'specialty' },
  { headerName: 'Спеціалізація', field: 'specialization' },
  { headerName: 'Тип програми магістра', field: 'masterType' },
  { headerName: 'Освітні програми', field: 'educationalPrograms' },
  { headerName: 'Структурний підрозділ', field: 'structuralUnit' },
  { headerName: 'Скорочений термін', field: 'isShortenedTerm', selected: ['так', 'ні'] },
  { headerName: 'Термін навчання', field: 'studyPeriod' },
  { headerName: 'Початок навчання', field: 'studyStart', isDate: true },
  { headerName: 'Закінчення навчання', field: 'studyEnd', isDate: true },
  { headerName: 'Дата застосування пропозиції', field: 'dateApplication', isDate: true },
  { headerName: 'Дата останньої зміни', field: 'lastChange', isDate: true },
  { headerName: 'Дата завантаження ліцензії', field: 'licenseDownload', isDate: true },
  { headerName: 'Підстава ліцензії', field: 'licenseBasis' },
  { headerName: 'МінКБР', field: 'minKBR' },
  { headerName: 'Регіональне замовлення від', field: 'regionalOrder' },
];

export const statementsColumns = [
  { headerName: 'Ід заявки', field: 'statementId' },
  { headerName: 'Ід персони', field: 'personaId' },
  { headerName: 'Тип пропозиції', field: 'proposeType', selected: ['Фіксована', 'Відкрита'] },
  { headerName: 'Чи іноземець', field: 'isForeigner', selected: ['Так', 'Ні'] },
  { headerName: 'Назва КП', field: 'offerName' },
  { headerName: 'ОКР', field: 'okr' },
  { headerName: 'Вступ на основі', field: 'admissionBased' },
  { headerName: 'Спеціальність', field: 'specialty' },
  { headerName: 'Спеціалізація', field: 'specialization' },
  { headerName: 'Форма навчання', field: 'studyForm', selected: ['Денна', 'Заочна'] },
  { headerName: 'Курс', field: 'course' },
  { headerName: 'Структурний підрозділ', field: 'structuralUnit' },
  { headerName: 'Чи скорочений термін навчання', field: 'isTrainingPeriodReduced', selected: ['Так', 'Ні'] },
  { headerName: 'Чи електронна заява', field: 'isElectronicApplication', selected: ['Так', 'Ні'] },
  { headerName: 'Вступник', field: 'statement' },
  { headerName: 'Контактний номер', field: 'contactNumber' },
  { headerName: 'Електронна адреса', field: 'electronicAddress' },
  { headerName: 'Стать', field: 'sex', selected: ['Чоловіча', 'Жіноча'] },
  { headerName: 'Чи громадянин України', field: 'isCitizenOfUkraine', selected: ['Так', 'Ні'] },
  { headerName: 'Статус заявки', field: 'statementStatus' },
  { headerName: 'Номер (шифр) особової справи', field: 'personalFileCode' },
  { headerName: 'Конкурсний бал', field: 'competitiveScore' },
  { headerName: 'Пріоритет', field: 'priority' },
  { headerName: 'Черговість в рейтингу з однаковою кількістю балів', field: 'sequenceRankingSameNumberOfPoints' },
  { headerName: 'Бере участь в конкурсі на місця державного та регіонального замовлення', field: 'isParticipatesCompetitionStateOrRegional', selected: ['Так', 'Ні'] },
  { headerName: 'Бере участь в конкурсі на місця за кошти фізичних та юридичних осіб', field: 'isParticipatesCompetitionIndividualsOrLegal', selected: ['Так', 'Ні'] },
  { headerName: 'Тип конкурсу, за яким отримано рекомендацію', field: 'typeCompetitionRecomendation' },
  { headerName: 'Чи рекомендовано за співбесідою', field: 'isRecommendedByInterview', selected: ['Так', 'Ні'] },
  { headerName: 'Чи подано оригінал', field: 'isOriginalSubmitted', selected: ['Так', 'Ні'] },
  { headerName: 'Чи подано довідку про місцезнаходження оригіналів', field: 'isLocationOriginalsProvided', selected: ['Так', 'Ні'] },
  { headerName: 'Категорія заяви іноземця', field: 'categoryForeigner' },
  { headerName: 'Пільгові категорії', field: 'preferentialCategories' },
  { headerName: 'Номер акту', field: 'actNumber' },
  { headerName: 'Причини скасування', field: 'cancelReason' },
  { headerName: 'Особа претендує на зарахування 200 балів', field: 'isPersonClaims200', selected: ['Так', 'Ні'] },
  { headerName: 'Особа претендує на застосування сільського коефіцієнту', field: 'isPersonVillageСoef', selected: ['Так', 'Ні'] },
  { headerName: 'Претендує на квоту 3', field: 'isPretendQuota3', selected: ['Так', 'Ні'] },
  { headerName: 'Наказ про зарахування', field: 'enrollmentOrder' },
  { headerName: 'Причини відрахування', field: 'deductionReasons' },
  { headerName: 'Претендує на контракт', field: 'isPretendContract', selected: ['Так', 'Ні'] },
  { headerName: 'Претендує на бюджет', field: 'isPretendBudget', selected: ['Так', 'Ні'] },
  { headerName: 'Причина допуску лише на контракт', field: 'reasonForContractOnly' },
  { headerName: "Опис причини допуску лише на контракт для причини 'Інша'", field: 'reasonForContractOnlyOther' },
  { headerName: 'Чи здобувався ОКР уже за бюджет', field: 'isObtainedForBudget' },
  { headerName: 'Право здобувати іншу освіту за бюджет', field: 'receiveOtherEducationForBudget', selected: ['Так', 'Ні'] },
  { headerName: 'Чи вступ на ту саму або споріднену галузь', field: 'isIntroductionToTheSame', selected: ['Так', 'Ні'] },
  { headerName: 'Чи здобуває ступінь(рівень) або вищий', field: 'isGetDegree', selected: ['Так', 'Ні'] },
  { headerName: 'Чи потрібно пройти додаткові вступні випробування', field: 'isNeedToPassAdditionalExams', selected: ['Так', 'Ні'] },
  { headerName: 'Тип документа', field: 'documentType' },
  { headerName: 'Серія документа', field: 'documentSeries' },
  { headerName: 'Номер документа', field: 'documentNumber' },
  { headerName: 'Дата видачі документа', field: 'documentIssuanceDate', isDate: true },
  { headerName: 'Ким видано', field: 'documentIssuedBy' },
  { headerName: 'Відзнака', field: 'honor' },
  { headerName: 'Сканкопія додана', field: 'isScanningAdded', selected: ['Так', 'Ні'] },
  { headerName: 'Час додання заяви до ЄДЕБО', field: 'addedTimeInEDEBO', isDate: true },
  { headerName: 'Потрібно внести зміни в ЗНО', field: 'isNeedChangeZNO', selected: ['Так', 'Ні'] },
  { headerName: 'Чи рекомендовано за результатом адресного розміщення державного замовлення', field: 'isRecommendedByResultOfAddressBudgetOrder', selected: ['Так', 'Ні'] },
  { headerName: 'Тип конкурсу, за яким одержано рекомендацію за результатом адресного розміщення ДЗ', field: 'typeCompetitionRecomendationOfAddress' },
  { headerName: 'Пріоритет заяви, яка отримала рекомендацію за результатом адресного розміщення ДЗ', field: 'priorityStatement' },
  { headerName: 'Чи отримав рекомендацію на анульовану конкурсну пропозицію, за результатом адресного розміщення державного замовлення', field: 'isRecommendedOnCanceled', selected: ['Так', 'Ні'] },
  { headerName: 'Час останньої зміни', field: 'lastTimeChange', isDate: true },
  { headerName: 'Додав заяву', field: 'addedStatement' },
  { headerName: 'Середній бал документа про освіту', field: 'averageEducationDocumentScore' },
  { headerName: 'ЗНО.Українська мова', field: 'znoUkrainian' },
  { headerName: 'ЗНО.Українська мова та література', field: 'znoUkrainianLiterature' },
  { headerName: 'ЗНО.Історія України', field: 'znoUkrainianHistory' },
  { headerName: 'ЗНО.Математика', field: 'znoMathematics' },
  { headerName: 'ЗНО.Біологія', field: 'znoBiology' },
  { headerName: 'ЗНО.Географія', field: 'znoGeography' },
  { headerName: 'ЗНО.Фізика', field: 'znoPhysics' },
  { headerName: 'ЗНО.Хімія', field: 'znoChemistry' },
  { headerName: 'ЗНО.Англійська мова', field: 'znoEnglish' },
  { headerName: 'ЗНО.Французька мова', field: 'znoFrench' },
  { headerName: 'ЗНО.Німецька мова', field: 'znoGerman' },
  { headerName: 'ЗНО.Іспанська мова', field: 'znoSpanish' },
  { headerName: 'ДПО', field: 'dpo' },
  { headerName: 'ДПО.Серія', field: 'dpoSeries' },
  { headerName: 'ДПО.Номер', field: 'dpoNumber' },
  { headerName: 'ДПО.Дата видачі', field: 'dpoIssueDate' },
  { headerName: 'ДПО.Дійсний до', field: 'dpoValidUntil' },
  { headerName: 'РНОКПП', field: 'rnokpp' },
];
